name: Daily Email Reminder

on:
  schedule:
    - cron: '0 16 * * *'   # 9:30 PM IST
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin yagmail

      - name: Write Firebase key
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          echo "$FIREBASE_KEY" > firebase_key.json

      - name: Run Reminder Script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python .github/scripts/send_reminders.py
