name: Daily Email Reminder

on:
  schedule:
    # Runs every day at 16:00 UTC (9:30 PM IST)
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Reminder
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily CalorieMate Reminder"
          to: madhumitabhat4503@gmail.com
          from: CalorieMate Bot <youruseremail@example.com>
          body: "Hello! This is your daily CalorieMate reminder to check your health stats and update your meals."
          secure: true
